# Generated by Django 2.1.7 on 2019-03-31 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anncouncement',
            new_name='Announcement',
        ),
    ]
