# Generated by Django 2.1.7 on 2019-03-31 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20190331_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-create_time'], 'verbose_name': '公告'},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='admin',
        ),
    ]
