# Generated by Django 2.1.7 on 2019-03-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_member_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='用户名'),
        ),
    ]
