# Generated by Django 2.1.7 on 2019-03-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190330_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(default='233', max_length=64, unique=True, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
