# Generated by Django 2.1.7 on 2019-03-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_auto_20190330_1032'),
        ('accounts', '0004_auto_20190330_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='topic.Team', verbose_name='队伍'),
        ),
    ]
