# Generated by Django 2.1.7 on 2019-03-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0006_auto_20190330_1557'),
        ('accounts', '0006_solveproblem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solveproblem',
            unique_together={('member', 'topic')},
        ),
    ]
