# Generated by Django 2.1.7 on 2019-03-31 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190330_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_leader',
            field=models.BooleanField(default=False, verbose_name='是否为队长'),
        ),
    ]
