# Generated by Django 2.1.7 on 2019-03-31 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190331_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='uuid',
            field=models.CharField(default=uuid.UUID('2f714534-6a4c-4a6a-8c0a-4575b278f87a'), max_length=8, unique=True, verbose_name='队伍ID'),
        ),
    ]
