# Generated by Django 2.1.7 on 2019-03-31 09:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190331_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='uuid',
            field=models.CharField(default=uuid.UUID('e569d654-f330-409f-8a55-51a35754fd06'), max_length=8, unique=True, verbose_name='队伍ID'),
        ),
    ]
