# Generated by Django 2.1.7 on 2019-03-31 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190331_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='uuid',
            field=models.CharField(default=uuid.UUID('8485a6a6-a6fb-4fee-9562-d537586190e6'), max_length=8, unique=True, verbose_name='队伍ID'),
        ),
    ]
