# Generated by Django 2.1.7 on 2019-03-31 09:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190331_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='uuid',
            field=models.CharField(default=uuid.UUID('cf8264cc-4353-4012-84d3-217b421db52f'), max_length=8, unique=True, verbose_name='队伍ID'),
        ),
    ]
