# Generated by Django 2.1.7 on 2019-03-31 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190331_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='uuid',
            field=models.CharField(default=uuid.UUID('65698029-8781-4c3b-ada4-e954385ebbcb'), max_length=8, unique=True, verbose_name='队伍ID'),
        ),
    ]
