# Generated by Django 2.1.7 on 2019-03-31 14:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190331_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solveproblem',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.TopicInstance', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='team',
            name='uuid',
            field=models.CharField(default=uuid.UUID('bff9908a-79b0-4296-844f-680a5b7736e2'), max_length=8, unique=True, verbose_name='队伍ID'),
        ),
    ]
