# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-30 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='队伍名称')),
                ('uuid', models.CharField(max_length=8, unique=True, verbose_name='队伍ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_status', models.CharField(choices=[('ready', '未BUILD'), ('building', '正在build'), ('success', 'build成功'), ('fail', 'build失败')], default='ready', max_length=20, verbose_name='BUILD状态')),
                ('build_log', models.TextField(null=True, verbose_name='BUILD日志')),
                ('port', models.IntegerField(verbose_name='需要映射出来的端口')),
                ('build_type', models.CharField(choices=[('Dockerfile', 'Dockerfile'), ('DockerCompose', 'DockerCompose')], max_length=20, verbose_name='Build方式')),
                ('title', models.CharField(max_length=60, verbose_name='题目名称')),
                ('build_name', models.CharField(max_length=80, verbose_name='英文名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('type', models.CharField(choices=[('bin', '二进制'), ('web', 'web安全'), ('misc', '杂项'), ('pwn', 'PWN')], max_length=20, verbose_name='题目类型')),
                ('introduction', models.TextField(verbose_name='题目简介')),
                ('flag_is_unique', models.BooleanField(verbose_name='答案是否唯一')),
                ('exec_command', models.TextField(null=True, verbose_name='需要执行的命令')),
                ('zip_file', models.FileField(upload_to='docker/938f245c-52a6-11e9-b06f-b025aa148d03', verbose_name='部署的压缩包')),
                ('image_id', models.CharField(max_length=16, null=True, verbose_name='镜像ID')),
                ('in_group', models.BooleanField(default=False, verbose_name='是否加入试卷')),
                ('flag', models.CharField(max_length=50, null=True, verbose_name='FLAG')),
            ],
        ),
        migrations.CreateModel(
            name='TopicInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(verbose_name='题目端口')),
                ('flag', models.CharField(max_length=50, verbose_name='题目答案')),
                ('container_id', models.CharField(max_length=16, null=True, verbose_name='容器ID')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topic.Team')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Topic')),
            ],
        ),
    ]
