# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-24 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='path',
        ),
    ]
