# Generated by Django 2.1.7 on 2019-03-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='zip_file',
            field=models.FileField(upload_to='docker/f9a8c010-52bd-11e9-b95d-b025aa148d03', verbose_name='部署的压缩包'),
        ),
    ]
