# Generated by Django 2.1.7 on 2019-03-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20190330_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='zip_file',
            field=models.FileField(upload_to='docker/446e1bb4-52d1-11e9-885c-b025aa148d03', verbose_name='部署的压缩包'),
        ),
    ]
