# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-26 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_topicgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='zip_file',
            field=models.FileField(default=222, upload_to='', verbose_name='部署的压缩包'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='build_type',
            field=models.CharField(choices=[('Dockerfile', 'Dockerfile'), ('DockerCompose', 'DockerCompose')], max_length=20, verbose_name='Build方式'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='type',
            field=models.CharField(choices=[('bin', '二进制'), ('web', 'web安全'), ('misc', '杂项'), ('pwn', 'PWN')], max_length=20, verbose_name='题目类型'),
        ),
    ]
