# Generated by Django 2.1.7 on 2019-03-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_auto_20190330_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='队伍名称'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='zip_file',
            field=models.FileField(upload_to='docker/1c4df522-52d7-11e9-a6ec-b025aa148d03', verbose_name='部署的压缩包'),
        ),
    ]
