# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-26 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_auto_20190326_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicgroup',
            name='topic_id',
        ),
        migrations.AddField(
            model_name='topicgroup',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='topic.Topic', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='zip_file',
            field=models.FileField(upload_to='docker/c2a915e6-5007-11e9-8c93-b025aa148d03', verbose_name='部署的压缩包'),
        ),
    ]
