# Generated by Django 2.1.7 on 2019-03-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_auto_20190330_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='integral',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='zip_file',
            field=models.FileField(upload_to='docker/535c8a6a-52e6-11e9-9a31-b025aa148d03', verbose_name='部署的压缩包'),
        ),
    ]
