# Generated by Django 2.1.7 on 2019-03-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0005_auto_20190330_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='zip_file',
            field=models.FileField(upload_to='docker/85f5740a-5304-11e9-9c4f-2016d8f09a47', verbose_name='部署的压缩包'),
        ),
    ]
