# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-28 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0005_auto_20190326_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='build_log',
            field=models.TextField(null=True, verbose_name='BUILD日志'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='zip_file',
            field=models.FileField(upload_to='docker/2943575c-516c-11e9-a197-2016d8f09a47', verbose_name='部署的压缩包'),
        ),
    ]
