# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-28 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0006_auto_20190328_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='BUILD_STATUS',
            field=models.CharField(choices=[('ready', '未BUILD'), ('building', '正在build'), ('success', 'build成功'), ('fail', 'build失败')], default='ready', max_length=20, verbose_name='BUILD状态'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='zip_file',
            field=models.FileField(upload_to='docker/0cb628bc-5171-11e9-a417-2016d8f09a47', verbose_name='部署的压缩包'),
        ),
        migrations.AlterField(
            model_name='topicgroup',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='topic.Topic'),
        ),
    ]
