# Generated by Django 2.1.7 on 2019-03-31 03:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0006_auto_20190330_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='uuid',
            field=models.CharField(default=uuid.UUID('d7e1ddd0-5363-11e9-a1e2-b025aa148d03'), max_length=8, unique=True, verbose_name='队伍ID'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='zip_file',
            field=models.FileField(upload_to='docker/d7e2072e-5363-11e9-a1e2-b025aa148d03', verbose_name='部署的压缩包'),
        ),
    ]
