# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-28 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0007_auto_20190328_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='BUILD_STATUS',
            new_name='build_status',
        ),
        migrations.AlterField(
            model_name='topic',
            name='zip_file',
            field=models.FileField(upload_to='docker/3aa5d024-5171-11e9-90aa-2016d8f09a47', verbose_name='部署的压缩包'),
        ),
    ]
