# Generated by Django 2.1.7 on 2019-03-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190331_0731'),
        ('topic', '0008_auto_20190331_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicinstance',
            name='team',
        ),
        migrations.RemoveField(
            model_name='topicinstance',
            name='topic',
        ),
        migrations.AlterField(
            model_name='topic',
            name='zip_file',
            field=models.FileField(upload_to='docker/ebbb217a-b9ef-43ec-88ff-69046e8a5c16', verbose_name='部署的压缩包'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TopicInstance',
        ),
    ]
