# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-28 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0008_auto_20190328_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image_id',
            field=models.CharField(max_length=16, null=True, verbose_name='镜像ID'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='zip_file',
            field=models.FileField(upload_to='docker/502ef026-51ab-11e9-b6af-b025aa148d03', verbose_name='部署的压缩包'),
        ),
    ]
