# Generated by Django 2.1.7 on 2019-03-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0009_auto_20190331_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='zip_file',
            field=models.FileField(upload_to='docker/753dd5cd-e520-41eb-9f21-8d731bc8df26', verbose_name='部署的压缩包'),
        ),
    ]
