# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-29 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0010_auto_20190329_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicgroup',
            name='topic',
        ),
        migrations.AddField(
            model_name='topic',
            name='in_group',
            field=models.BooleanField(default=False, verbose_name='是否加入试卷'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='zip_file',
            field=models.FileField(upload_to='docker/57d421f4-5235-11e9-88a8-b025aa148d03', verbose_name='部署的压缩包'),
        ),
        migrations.DeleteModel(
            name='TopicGroup',
        ),
    ]
