# Generated by Django 2.1.7 on 2019-03-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0012_auto_20190331_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='zip_file',
            field=models.FileField(upload_to='docker/7d3c0f51-b368-4c3d-94db-010947ca2893', verbose_name='部署的压缩包'),
        ),
    ]
