# Generated by Django 2.1.7 on 2019-03-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0013_auto_20190331_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='类型')),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='type',
            field=models.ForeignKey(on_delete='PROTECT', to='topic.TopicType', verbose_name='题目类型'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='zip_file',
            field=models.FileField(upload_to='docker/12728233-7e51-40ad-8cec-7f0390856d40', verbose_name='部署的压缩包'),
        ),
    ]
