# Generated by Django 2.1.7 on 2019-03-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0014_auto_20190331_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topictype',
            options={'verbose_name': '类型'},
        ),
        migrations.AlterField(
            model_name='topic',
            name='zip_file',
            field=models.FileField(upload_to='docker/c93d06fb-e522-4dda-8c9a-9d5eeb2bcc74', verbose_name='部署的压缩包'),
        ),
    ]
